| ID (Nec.) | Fonte (Stakeholder) | Método de Elicitação | Descrição da Necessidade (O que a PI precisa?) | Justificativa / Valor (Por que a PI precisa?) | Prioridade (MoSCoW) | Status de Validação | Observações |
| :---: | :--- | :--- | :--- | :--- | :---: | :---: | :--- |
| **NEC-001** | STK-002 (Especialista de Negócio - Docente) | Workshop | "Eu preciso de um sistema simples e intuitivo para criar e configurar missões e desafios para os meus alunos." | "Hoje, perco muito tempo formatando atividades; o XPASS deve simplificar a aplicação da gamificação em aula." | M | Validado | Essencial para o core do produto. A simplicidade é chave para a adoção pelo docente. |
| **NEC-002** | STK-003 (Representante de Usuário - Aluno) | Entrevista | "Eu preciso que a plataforma funcione perfeitamente no meu celular, sem travar ou consumir muita bateria." | "A maioria dos alunos acessa o material fora de casa e durante o transporte. A experiência mobile é crítica para o engajamento." | M | Validado | Restrição do projeto (Flutter/Mobile) e vital para a retenção do usuário final. |
| **NEC-003** | STK-001 (Patrocinador Fictício) | Reunião (TAP) | "O sistema deve gerar relatórios automatizados de engajamento e desempenho para monitorar o risco de evasão." | "O TAP exige a meta de reduzir a evasão em 10%. Precisamos de dados mensuráveis para justificar o investimento (ROI)." | M | Validado | Requisito de negócio de alto nível, ligado diretamente aos objetivos do projeto. |
| **NEC-004** | STK-003 (Representante de Usuário - Aluno) | Entrevista | "Gostaria de receber recompensas (badges, moedas virtuais) que possam ser trocadas por algum benefício real, como bônus na nota ou créditos extracurriculares." | "A recompensa é o que motiva o aluno a se dedicar fora do período de provas. Precisa ter valor percebido." | M | Validado | Necessidade central de gamificação. A regra de bonificação deve ser configurável pelo docente. |
| **NEC-005** | STK-007 (Coordenador de Curso Fictício) | Formulário | "O XPASS precisa estar seguro e garantir que apenas alunos e professores autorizados tenham acesso aos seus dados e notas." | "É uma exigência regulatória (LGPD/Geral) garantir a privacidade dos dados acadêmicos." | M | Validado | Requisito Não Funcional (Segurança) de alta prioridade. |
| **NEC-006** | STK-002 (Especialista de Negócio - Docente) | Workshop | "Eu gostaria de ter um banco de questões que eu possa reutilizar e misturar para criar novos desafios rapidamente." | "Reutilizar questões poupa muito tempo e permite que eu crie vários desafios em menos de uma hora." | S | Validado | Importante para a eficiência e usabilidade do professor, mas o sistema base funciona sem ele. |
| **NEC-007** | STK-004 (Líder Técnico Fictício) | Análise Técnica | "O backend deve ser capaz de suportar pelo menos 5.000 usuários simultâneos com tempo de resposta inferior a 3 segundos." | "Estimativa de pico de acesso em período de provas ou lançamento de missões. A performance é crítica para a UX." | M | Pendente | Necessita de validação com o STK-007 (Coordenador) para confirmar o volume exato de alunos. |
| **NEC-008** | STK-003 (Representante de Usuário - Aluno) | Brainstorming | "Era bom se o sistema tivesse um chat/fórum interno para que eu pudesse pedir ajuda em missões ou discutir a matéria com outros colegas." | "Facilita a colaboração e a troca de conhecimento entre os alunos, reforçando o aprendizado." | C | Validado | Funcionalidade nice to have; pode ser implementada em uma versão futura. |
